<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BusinessHourShopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $params = [
            ['id' => 1, 'shop_id' => '1', 'business_hour_id' => '11'],
            ['id' => 2, 'shop_id' => '1', 'business_hour_id' => '12'],
            ['id' => 3, 'shop_id' => '1', 'business_hour_id' => '13'],
            ['id' => 4, 'shop_id' => '1', 'business_hour_id' => '14'],
            ['id' => 5, 'shop_id' => '1', 'business_hour_id' => '15'],
            ['id' => 6, 'shop_id' => '1', 'business_hour_id' => '16'],
            ['id' => 7, 'shop_id' => '1', 'business_hour_id' => '17'],
            ['id' => 8, 'shop_id' => '1', 'business_hour_id' => '18'],
            ['id' => 9, 'shop_id' => '1', 'business_hour_id' => '19'],
            ['id' => 10, 'shop_id' => '1', 'business_hour_id' => '20'],
            ['id' => 11, 'shop_id' => '2', 'business_hour_id' => '10'],
            ['id' => 12, 'shop_id' => '2', 'business_hour_id' => '11'],
            ['id' => 13, 'shop_id' => '2', 'business_hour_id' => '12'],
            ['id' => 14, 'shop_id' => '2', 'business_hour_id' => '13'],
            ['id' => 15, 'shop_id' => '2', 'business_hour_id' => '14'],
            ['id' => 16, 'shop_id' => '2', 'business_hour_id' => '15'],
            ['id' => 17, 'shop_id' => '2', 'business_hour_id' => '16'],
            ['id' => 18, 'shop_id' => '2', 'business_hour_id' => '17'],
            ['id' => 19, 'shop_id' => '2', 'business_hour_id' => '18'],
            ['id' => 20, 'shop_id' => '2', 'business_hour_id' => '19'],
            ['id' => 21, 'shop_id' => '2', 'business_hour_id' => '20'],
            ['id' => 22, 'shop_id' => '2', 'business_hour_id' => '21'],
            ['id' => 23, 'shop_id' => '2', 'business_hour_id' => '22'],
            ['id' => 24, 'shop_id' => '3', 'business_hour_id' => '17'],
            ['id' => 25, 'shop_id' => '3', 'business_hour_id' => '18'],
            ['id' => 26, 'shop_id' => '3', 'business_hour_id' => '19'],
            ['id' => 27, 'shop_id' => '3', 'business_hour_id' => '20'],
            ['id' => 28, 'shop_id' => '3', 'business_hour_id' => '21'],
            ['id' => 29, 'shop_id' => '3', 'business_hour_id' => '22'],
            ['id' => 30, 'shop_id' => '3', 'business_hour_id' => '23'],
            ['id' => 31, 'shop_id' => '4', 'business_hour_id' => '11'],
            ['id' => 32, 'shop_id' => '4', 'business_hour_id' => '12'],
            ['id' => 33, 'shop_id' => '4', 'business_hour_id' => '13'],
            ['id' => 34, 'shop_id' => '4', 'business_hour_id' => '17'],
            ['id' => 35, 'shop_id' => '4', 'business_hour_id' => '18'],
            ['id' => 36, 'shop_id' => '4', 'business_hour_id' => '19'],
            ['id' => 37, 'shop_id' => '4', 'business_hour_id' => '20'],
            ['id' => 38, 'shop_id' => '5', 'business_hour_id' => '11'],
            ['id' => 39, 'shop_id' => '5', 'business_hour_id' => '12'],
            ['id' => 40, 'shop_id' => '5', 'business_hour_id' => '13'],
            ['id' => 41, 'shop_id' => '5', 'business_hour_id' => '17'],
            ['id' => 42, 'shop_id' => '5', 'business_hour_id' => '18'],
            ['id' => 43, 'shop_id' => '5', 'business_hour_id' => '19'],
            ['id' => 44, 'shop_id' => '5', 'business_hour_id' => '20'],
            ['id' => 45, 'shop_id' => '5', 'business_hour_id' => '21'],
            ['id' => 46, 'shop_id' => '5', 'business_hour_id' => '22'],
            ['id' => 47, 'shop_id' => '5', 'business_hour_id' => '23'],
            ['id' => 48, 'shop_id' => '6', 'business_hour_id' => '10'],
            ['id' => 49, 'shop_id' => '6', 'business_hour_id' => '11'],
            ['id' => 50, 'shop_id' => '6', 'business_hour_id' => '12'],
            ['id' => 51, 'shop_id' => '6', 'business_hour_id' => '13'],
            ['id' => 52, 'shop_id' => '6', 'business_hour_id' => '14'],
            ['id' => 53, 'shop_id' => '6', 'business_hour_id' => '15'],
            ['id' => 54, 'shop_id' => '6', 'business_hour_id' => '16'],
            ['id' => 55, 'shop_id' => '6', 'business_hour_id' => '17'],
            ['id' => 56, 'shop_id' => '6', 'business_hour_id' => '18'],
            ['id' => 57, 'shop_id' => '6', 'business_hour_id' => '19'],
            ['id' => 58, 'shop_id' => '6', 'business_hour_id' => '20'],
            ['id' => 59, 'shop_id' => '6', 'business_hour_id' => '21'],
            ['id' => 60, 'shop_id' => '6', 'business_hour_id' => '22'],
            ['id' => 61, 'shop_id' => '7', 'business_hour_id' => '11'],
            ['id' => 62, 'shop_id' => '7', 'business_hour_id' => '12'],
            ['id' => 63, 'shop_id' => '7', 'business_hour_id' => '13'],
            ['id' => 64, 'shop_id' => '7', 'business_hour_id' => '17'],
            ['id' => 65, 'shop_id' => '7', 'business_hour_id' => '18'],
            ['id' => 66, 'shop_id' => '7', 'business_hour_id' => '19'],
            ['id' => 67, 'shop_id' => '7', 'business_hour_id' => '20'],
            ['id' => 68, 'shop_id' => '8', 'business_hour_id' => '11'],
            ['id' => 69, 'shop_id' => '8', 'business_hour_id' => '12'],
            ['id' => 70, 'shop_id' => '8', 'business_hour_id' => '13'],
            ['id' => 71, 'shop_id' => '8', 'business_hour_id' => '17'],
            ['id' => 72, 'shop_id' => '8', 'business_hour_id' => '18'],
            ['id' => 73, 'shop_id' => '8', 'business_hour_id' => '19'],
            ['id' => 74, 'shop_id' => '8', 'business_hour_id' => '20'],
            ['id' => 75, 'shop_id' => '8', 'business_hour_id' => '21'],
            ['id' => 76, 'shop_id' => '8', 'business_hour_id' => '22'],
            ['id' => 77, 'shop_id' => '8', 'business_hour_id' => '23'],
            ['id' => 78, 'shop_id' => '9', 'business_hour_id' => '17'],
            ['id' => 79, 'shop_id' => '9', 'business_hour_id' => '18'],
            ['id' => 80, 'shop_id' => '9', 'business_hour_id' => '19'],
            ['id' => 81, 'shop_id' => '9', 'business_hour_id' => '20'],
            ['id' => 82, 'shop_id' => '9', 'business_hour_id' => '21'],
            ['id' => 83, 'shop_id' => '9', 'business_hour_id' => '22'],
            ['id' => 84, 'shop_id' => '9', 'business_hour_id' => '23'],
            ['id' => 85, 'shop_id' => '10', 'business_hour_id' => '11'],
            ['id' => 86, 'shop_id' => '10', 'business_hour_id' => '12'],
            ['id' => 87, 'shop_id' => '10', 'business_hour_id' => '13'],
            ['id' => 88, 'shop_id' => '10', 'business_hour_id' => '14'],
            ['id' => 89, 'shop_id' => '10', 'business_hour_id' => '15'],
            ['id' => 90, 'shop_id' => '10', 'business_hour_id' => '16'],
            ['id' => 91, 'shop_id' => '10', 'business_hour_id' => '17'],
            ['id' => 92, 'shop_id' => '10', 'business_hour_id' => '18'],
            ['id' => 93, 'shop_id' => '10', 'business_hour_id' => '19'],
            ['id' => 94, 'shop_id' => '10', 'business_hour_id' => '20'],
            ['id' => 95, 'shop_id' => '11', 'business_hour_id' => '10'],
            ['id' => 96, 'shop_id' => '11', 'business_hour_id' => '11'],
            ['id' => 97, 'shop_id' => '11', 'business_hour_id' => '12'],
            ['id' => 98, 'shop_id' => '11', 'business_hour_id' => '13'],
            ['id' => 99, 'shop_id' => '11', 'business_hour_id' => '14'],
            ['id' => 100, 'shop_id' => '11', 'business_hour_id' => '15'],
            ['id' => 101, 'shop_id' => '11', 'business_hour_id' => '16'],
            ['id' => 102, 'shop_id' => '11', 'business_hour_id' => '17'],
            ['id' => 103, 'shop_id' => '11', 'business_hour_id' => '18'],
            ['id' => 104, 'shop_id' => '11', 'business_hour_id' => '19'],
            ['id' => 105, 'shop_id' => '11', 'business_hour_id' => '20'],
            ['id' => 106, 'shop_id' => '11', 'business_hour_id' => '21'],
            ['id' => 107, 'shop_id' => '11', 'business_hour_id' => '22'],
            ['id' => 108, 'shop_id' => '12', 'business_hour_id' => '10'],
            ['id' => 109, 'shop_id' => '12', 'business_hour_id' => '11'],
            ['id' => 110, 'shop_id' => '12', 'business_hour_id' => '12'],
            ['id' => 111, 'shop_id' => '12', 'business_hour_id' => '13'],
            ['id' => 112, 'shop_id' => '12', 'business_hour_id' => '14'],
            ['id' => 113, 'shop_id' => '12', 'business_hour_id' => '15'],
            ['id' => 114, 'shop_id' => '12', 'business_hour_id' => '16'],
            ['id' => 115, 'shop_id' => '12', 'business_hour_id' => '17'],
            ['id' => 116, 'shop_id' => '12', 'business_hour_id' => '18'],
            ['id' => 117, 'shop_id' => '12', 'business_hour_id' => '19'],
            ['id' => 118, 'shop_id' => '12', 'business_hour_id' => '20'],
            ['id' => 119, 'shop_id' => '12', 'business_hour_id' => '21'],
            ['id' => 120, 'shop_id' => '12', 'business_hour_id' => '22'],
            ['id' => 121, 'shop_id' => '13', 'business_hour_id' => '17'],
            ['id' => 122, 'shop_id' => '13', 'business_hour_id' => '18'],
            ['id' => 123, 'shop_id' => '13', 'business_hour_id' => '19'],
            ['id' => 124, 'shop_id' => '13', 'business_hour_id' => '20'],
            ['id' => 125, 'shop_id' => '13', 'business_hour_id' => '21'],
            ['id' => 126, 'shop_id' => '13', 'business_hour_id' => '22'],
            ['id' => 127, 'shop_id' => '13', 'business_hour_id' => '23'],
            ['id' => 128, 'shop_id' => '14', 'business_hour_id' => '11'],
            ['id' => 129, 'shop_id' => '14', 'business_hour_id' => '12'],
            ['id' => 130, 'shop_id' => '14', 'business_hour_id' => '13'],
            ['id' => 131, 'shop_id' => '14', 'business_hour_id' => '14'],
            ['id' => 132, 'shop_id' => '14', 'business_hour_id' => '15'],
            ['id' => 133, 'shop_id' => '14', 'business_hour_id' => '16'],
            ['id' => 134, 'shop_id' => '14', 'business_hour_id' => '17'],
            ['id' => 135, 'shop_id' => '14', 'business_hour_id' => '18'],
            ['id' => 136, 'shop_id' => '14', 'business_hour_id' => '19'],
            ['id' => 137, 'shop_id' => '14', 'business_hour_id' => '20'],
            ['id' => 138, 'shop_id' => '15', 'business_hour_id' => '11'],
            ['id' => 139, 'shop_id' => '15', 'business_hour_id' => '12'],
            ['id' => 140, 'shop_id' => '15', 'business_hour_id' => '13'],
            ['id' => 141, 'shop_id' => '15', 'business_hour_id' => '17'],
            ['id' => 142, 'shop_id' => '15', 'business_hour_id' => '18'],
            ['id' => 143, 'shop_id' => '15', 'business_hour_id' => '19'],
            ['id' => 144, 'shop_id' => '15', 'business_hour_id' => '20'],
            ['id' => 145, 'shop_id' => '15', 'business_hour_id' => '21'],
            ['id' => 146, 'shop_id' => '15', 'business_hour_id' => '22'],
            ['id' => 147, 'shop_id' => '15', 'business_hour_id' => '23'],
            ['id' => 148, 'shop_id' => '16', 'business_hour_id' => '17'],
            ['id' => 149, 'shop_id' => '16', 'business_hour_id' => '18'],
            ['id' => 150, 'shop_id' => '16', 'business_hour_id' => '19'],
            ['id' => 151, 'shop_id' => '16', 'business_hour_id' => '20'],
            ['id' => 152, 'shop_id' => '16', 'business_hour_id' => '21'],
            ['id' => 153, 'shop_id' => '16', 'business_hour_id' => '22'],
            ['id' => 154, 'shop_id' => '16', 'business_hour_id' => '23'],
            ['id' => 155, 'shop_id' => '17', 'business_hour_id' => '11'],
            ['id' => 156, 'shop_id' => '17', 'business_hour_id' => '12'],
            ['id' => 157, 'shop_id' => '17', 'business_hour_id' => '13'],
            ['id' => 158, 'shop_id' => '17', 'business_hour_id' => '14'],
            ['id' => 159, 'shop_id' => '17', 'business_hour_id' => '15'],
            ['id' => 160, 'shop_id' => '17', 'business_hour_id' => '16'],
            ['id' => 161, 'shop_id' => '17', 'business_hour_id' => '17'],
            ['id' => 162, 'shop_id' => '17', 'business_hour_id' => '18'],
            ['id' => 163, 'shop_id' => '17', 'business_hour_id' => '19'],
            ['id' => 164, 'shop_id' => '17', 'business_hour_id' => '20'],
            ['id' => 165, 'shop_id' => '18', 'business_hour_id' => '10'],
            ['id' => 166, 'shop_id' => '18', 'business_hour_id' => '11'],
            ['id' => 167, 'shop_id' => '18', 'business_hour_id' => '12'],
            ['id' => 168, 'shop_id' => '18', 'business_hour_id' => '13'],
            ['id' => 169, 'shop_id' => '18', 'business_hour_id' => '14'],
            ['id' => 170, 'shop_id' => '18', 'business_hour_id' => '15'],
            ['id' => 171, 'shop_id' => '18', 'business_hour_id' => '16'],
            ['id' => 172, 'shop_id' => '18', 'business_hour_id' => '17'],
            ['id' => 173, 'shop_id' => '18', 'business_hour_id' => '18'],
            ['id' => 174, 'shop_id' => '18', 'business_hour_id' => '19'],
            ['id' => 175, 'shop_id' => '18', 'business_hour_id' => '20'],
            ['id' => 176, 'shop_id' => '18', 'business_hour_id' => '21'],
            ['id' => 177, 'shop_id' => '18', 'business_hour_id' => '22'],
            ['id' => 178, 'shop_id' => '19', 'business_hour_id' => '11'],
            ['id' => 179, 'shop_id' => '19', 'business_hour_id' => '12'],
            ['id' => 180, 'shop_id' => '19', 'business_hour_id' => '13'],
            ['id' => 181, 'shop_id' => '19', 'business_hour_id' => '17'],
            ['id' => 182, 'shop_id' => '19', 'business_hour_id' => '18'],
            ['id' => 183, 'shop_id' => '19', 'business_hour_id' => '19'],
            ['id' => 184, 'shop_id' => '19', 'business_hour_id' => '20'],
            ['id' => 185, 'shop_id' => '20', 'business_hour_id' => '11'],
            ['id' => 186, 'shop_id' => '20', 'business_hour_id' => '12'],
            ['id' => 187, 'shop_id' => '20', 'business_hour_id' => '13'],
            ['id' => 188, 'shop_id' => '20', 'business_hour_id' => '14'],
            ['id' => 189, 'shop_id' => '20', 'business_hour_id' => '15'],
            ['id' => 190, 'shop_id' => '20', 'business_hour_id' => '16'],
            ['id' => 191, 'shop_id' => '20', 'business_hour_id' => '17'],
            ['id' => 192, 'shop_id' => '20', 'business_hour_id' => '18'],
            ['id' => 193, 'shop_id' => '20', 'business_hour_id' => '19'],
            ['id' => 194, 'shop_id' => '20', 'business_hour_id' => '20'],
        ];
        DB::table('business_hour_shop')->insert($params);
    }
}
